# 1.
SELECT * FROM czekoladki
WHERE masa BETWEEN 15 AND 24
UNION
SELECT * FROM czekoladki
WHERE koszt BETWEEN 0.15 AND 0.24

# 2.
SELECT * FROM czekoladki
WHERE masa BETWEEN 25 AND 35
INTERSECT
SELECT * FROM czekoladki
WHERE koszt NOT BETWEEN 0.25 AND 0.35;

# 3.
(SELECT * FROM czekoladki
WHERE masa BETWEEN 15 AND 24
INTERSECT
SELECT * FROM czekoladki
WHERE koszt BETWEEN 0.15 AND 0.24)
UNION
(SELECT * FROM czekoladki
WHERE masa BETWEEN 25 AND 35
INTERSECT
SELECT * FROM czekoladki
WHERE koszt BETWEEN 0.25 AND 0.35);

# 4.
SELECT * FROM czekoladki
WHERE masa BETWEEN 15 AND 24
INTERSECT
SELECT * FROM czekoladki
WHERE koszt BETWEEN 0.15 AND 0.24;

# 5.
(SELECT * FROM czekoladki
WHERE koszt NOT BETWEEN 0.15 AND 0.24
INTERSECT
SELECT * FROM czekoladki
WHERE koszt NOT BETWEEN 0.29 AND 0.35)
EXCEPT
SELECT * FROM czekoladki
WHERE masa BETWEEN 15 AND 24;